# Generated by Django 4.2.4 on 2023-08-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mobile',
            name='condition',
            field=models.CharField(choices=[('A grade', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='storage_capacity',
            field=models.CharField(choices=[('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB'), ('128', '128 GB'), ('256', '256 GB'), ('512', '512 GB'), ('1 tb', '1 TB')], max_length=10),
        ),
        migrations.AddField(
            model_name='mobile',
            name='categories',
            field=models.ManyToManyField(to='userside.category'),
        ),
    ]
