# Generated by Django 4.2.4 on 2023-08-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_category_alter_mobile_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image_1',
            field=models.ImageField(default='default_image.jpg', upload_to='mobile_images/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image_2',
            field=models.ImageField(default='default_image.jpg', upload_to='mobile_images/'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='mobile_images/'),
        ),
    ]
